### ISSUE TITLE
FSM for .*/.*

### ISSUE THREAD

**Issue by tgregoneil** [izuzak/noam#20]
The DFA for `.*/.*` gets generated as:

![screenshot from 2018-03-05 11 00 21](https://user-images.githubusercontent.com/518520/36988477-953afe7c-2064-11e8-9c08-eb489e60ee60.png)

However, it should have generated:
![screenshot from 2018-03-05 10 49 38](https://user-images.githubusercontent.com/518520/36988506-ab4ca440-2064-11e8-8b3b-6682ba5a561e.png)

For example, '//' is satisfied by the regex, but the DFA generated winds up in state 2, which is a non-final state.

**Comment by tgregoneil** [comment]
Presumably, for the two paths exiting state 0 and 1, the '.' really implies [^/], otherwise it would be an NFA, but it's a DFA that got generated. So, a '/' presented at state 0 requires a transition to state 1, thereby preventing '.' from matching '/'.  Similarly for exiting state 1 -- '/' forces transition to state 2, a non-final state.

**Comment by tgregoneil** [comment]
So then I tried [^/]*/.* as a check and this got generated:
![screenshot from 2018-03-05 11 18 41](https://user-images.githubusercontent.com/518520/36989352-1b564744-2067-11e8-84ae-64b2627937eb.png)

That generated DFA implies that metacharacters '[' and '^' inside the set spec are being interpreted as literal characters and not a set of choices and set complement, respectively.

**Comment by izuzak** [comment]
Hey @tgregoneil -- thanks for test-driving the tool and providing feedback! Please find answers and notes inline below.

> The DFA for .*/.* gets generated as:
>
> However, it should have generated:

No, that's not the case. The regular expression that's generated is expected.

The regular expression you provided as input is interpreted like this: any number or zero `.` characters, followed by a `/` character, followed by any number or zero `.` characters. When you define a DFA, you need to define the next state for each state and input. In the DFA you suggested, the next state for state `1` and input `/` is not defined, so the definition is incomplete. You _could_ assume that such undefined behaviors lead to an "error" state which the DFA can't get out of, but the DFA that the tool generates makes that "error" state explicit -- it's the state with index `2`. If you assume such an error state in your DFA, then your DFA and the DFA that the tool generates are equivalent.

> For example, '//' is satisfied by the regex, but the DFA generated winds up in state 2, which is a non-final state.

As far as I can tell, `//` is not satisfied by regex `.*/.*` unless you're interpreting the regex differently than above.

> Presumably, for the two paths exiting state 0 and 1, the '.' really implies [^/], 

Ah, no, that's not the case. In the language used by the tool, `.` is just the character `.` (see more notes below).

> So then I tried [^/]*/.* as a check and this got generated:
>
> That generated DFA implies that metacharacters '[' and '^' inside the set spec are being interpreted as literal characters and not a set of choices and set complement, respectively.

That's correct and is expected behavior for now. You will see what the tool considers a valid regex on the page:

http://ivanzuzak.info/noam/webapps/fsm_simulator/

"A valid regex consists of alphanumeric characters representing the set of input symbols (e.g. a, B, 9), the `$` character representing the empty string, the choice operator `+`, the Kleene operator `*`, and parentheses `(` and `)`. An example of a valid regex is: `(a+B)*(c9+$)+$`."

It's not a full regular expression language as in most modern programming languages. It's a reduced regular expression language used mostly for educational purposes.

Does that clear up the confusion?

**Comment by tgregoneil** [comment]
![screenshot from 2018-03-15 00 36 01](https://user-images.githubusercontent.com/518520/37446039-1244e474-27e9-11e8-9db9-9cf4c6a49375.png)

**Comment by tgregoneil** [comment]
And yes, `//` is satisfied by `.*/.*` This perl code demonstrates that:

![screenshot from 2018-03-15 00 44 16](https://user-images.githubusercontent.com/518520/37446245-0a8ad9cc-27ea-11e8-8e1c-e3e94c6f4e30.png)

**Comment by izuzak** [comment]
@tgregoneil Thanks for taking the time to explain your thoughts, but no -- you're not correct. 

The meaning of `.*/.*` is as I mentioned above: 

"any number or zero `.` characters, followed by a `/` character, followed by any number or zero `.` characters". 

The `.` character is just a character like any other. You could have written `a*/b*` and the meaning would then be:

"any number or zero `a` characters, followed by a `/` character, followed by any number or zero `a` characters". 

The generated FSM is a DFA and does finish in the expected dead state for the input string `//`.

The regex `.*/.*` does NOT match `//` as per the definition of the regular expression language used by this tool.

The regex `.*/.*` allows for at most one `/` character in the input string, which you can understand by looking at individual parts of the regex:
* the first `.*` part doesn't allow for any `/` characters -- it allows only `.` characters
* the `/` part allows for exactly one `/` character
* the second `.*` part doesn't allow for any `/` characters -- it allows only `.` characters

So if you input any string which has two `/` characters into the FSM generated from the regex `.*/.*`, then that string will end up in the dead state. That's true for `//`, for `././.`, for `...//`, for `//.../` and so on.

> And yes, // is satisfied by .*/.* This perl code demonstrates that:

Again, that's completely irrelevant because you are comparing apples to oranges. This tool does not use the same regular expression language as perl. The meaning of `.` is not the same as in perl.
