### ISSUE TITLE
Generated FSMs are massively overcomplicated

### ISSUE THREAD

**Issue by josephcsible** [izuzak/noam#31]
Consider the regex `(b+a*c)*aa*b`. When I put it in FSM2Regex, I get this horrible monstrosity: 

```
#states
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
#initial
0
#accepting
1
#alphabet
b
a
c
#transitions
6:b>7
4:$>6,8
7:$>5
10:a>11
8:$>9,10
11:$>10,9
12:c>13
9:$>12
13:$>5
2:$>3,4
5:$>4,3
14:a>15
3:$>14
18:a>19
16:$>17,18
19:$>18,17
15:$>16
20:b>21
17:$>20
0:$>2
21:$>1
```

Why not something much simpler, like this?

```
#states
s0
s1
s2
#initial
s0
#accepting
s2
#alphabet
a
b
c
#transitions
s0:a>s1
s0:b>s0
s0:c>s0
s1:a>s1
s1:b>s2
s1:c>s0
```

**Comment by ibudiselic** [comment]
It just applies a simple algorithm to generate an eNFA - it makes no attempt to make it small or simple.

Enter your regex in http://ivanzuzak.info/noam/webapps/fsm_simulator/ and pick a DFA as a type, and you will get something which is likely equivalent to what you wrote (I didn't actually look at it). Note that the DFA formalism we're using here requires there to be a transition for every pair of states and input symbols, so there's an extra state compared to what you wrote.

**Comment by josephcsible** [comment]
Yes, that one is indeed way better, and is equivalent to mine except for the extra state. Why does FSM2Regex not use that algorithm itself?

**Comment by izuzak** [comment]
Hi @josephcsible 👋 Thanks for sharing your thoughts here

> Why does FSM2Regex not use that algorithm itself?

Because that's not the point of that specific tool. We built different tools for different purposes in order to illustrate different processes. That said, I wouldn't be opposed to adding an option to that FSM2Regex tool which forces the tool to create a minimal DFA instead of an eNFA 

There's also a software library provided which you can use to build a custom tool which does what you want.
