### ISSUE TITLE
Incorrect simplification.

### ISSUE THREAD

**Issue by dlewissandy** [izuzak/noam#34]
a(a|aa) incorrectly simplifies to aa|aa

**Comment by izuzak** [comment]
Hey @dlewissandy 👋 

This is actually expected behavior since the `|` character isn't a special character in this tool -- it's just a regular character. I'm guessing you wanted to use the `+` character instead which does have special meaning (it's the choice operator). So, you'd try and simplify `a(a+aa)` which can't be simplified further.

Please see the instructions on [the site](http://ivanzuzak.info/noam/webapps/regex_simplifier/) which say:

> A valid regex consists of alphanumeric characters representing the set of input symbols (e.g. `a`, `B`, `9`), the `$` character representing the empty string, the choice operator `+`, the Kleene operator `*`, and parentheses `(` and `)`. An example of a valid regex is: `(a+B)*(c9+$)+$`.

Hope this helps!
