### ISSUE TITLE
Can you produce DFA with OR statement

### ISSUE THREAD

**Issue by jshef16** [izuzak/noam#40]
If you wanted to produce a DFA that can decide the language bb*a|a*b*, could your software do that?

**Comment by izuzak** [comment]
> If you wanted to produce a DFA that can decide the language `bb*a|a*b*`, could your software do that?

@jshef16 Yeah, you can do that. In http://ivanzuzak.info/noam/webapps/fsm_simulator/ you can input that regex, just use `+` instead of `|` since that's used for the choice operator. Also, select `DFA` from the dropdown.

Here's a screenshot:

<img width="1242" alt="Screen Shot 2021-05-22 at 21 53 21" src="https://user-images.githubusercontent.com/38924/119239269-38ce0f80-bb48-11eb-87d7-35100ad6cf79.png">

Hope this helps!
