### ISSUE TITLE
Generated DFA does not match input regex b*(d+a*)d

### ISSUE THREAD

**Issue by inburek** [izuzak/noam#41]
The DFA generator does not create the correct automaton for certain regular expressions.

To reproduce, generate DFA for `b*(d+a*)d`.

It will create a state machine that rejects the inputs `bdad` and `bddd`. 
The former was hand written as the obvious acceptable string, and the latter was generated with the "Unacceptable string" button after a few tries. They are both acceptable, and both are rejected by the DFA.

**Comment by izuzak** [comment]
Hi, @inburek 👋 I think there's been a misunderstanding about the meaning of the `+` symbol. As mentioned on [this page](http://ivanzuzak.info/noam/webapps/fsm_simulator/):

> A valid regex consists of alphanumeric characters representing the set of input symbols (e.g. `a`, `B`, `9`), the `$` character representing the empty string, **the choice operator `+`**, the Kleene operator `*`, and parentheses `(` and `)`. An example of a valid regex is: `(a+B)*(c9+$)+$`.

I highlighted the relevant part. With that in mind, the strings `bdad` and `bddd` are _not_ in the language defined by the regex `b*(d+a*)d` since `+` doesn't mean "one or more" but is a choice operator (i.e. an `OR`).

Hope this helps, and let me know if I misunderstood anything. :v:
