### ISSUE TITLE
How to create a DFA?

### ISSUE THREAD

**Issue by polkovnikov-ph** [izuzak/noam#7]
Does [online version](http://ivanzuzak.info/noam/webapps/fsm_simulator/) support DFA visualization from regex? I've found no such options in GUI.

**Comment by izuzak** [comment]
No, it doesn't. Basically, you want to input a regex, then convert it to an e-NFA, then convert that to a DFA, and then visualize the DFA? 

You could do the first few steps manually, using the noam, library, and then pass the resulting DFA to the  online version so that it visualizes it. Or if you'd like, you could make a pull request to improve the online version to support that. For example, you could add a "Generate DFA" button next to the existing  "Generate" button. That button would do the conversion and then visualize the resulting DFA and use that for simulation.
